name: Lint and Trivy Scan

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  lint:
    name: Lint Code with Super-Linter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Super-Linter
        uses: github/super-linter/slim@v6
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
          VALIDATE_ALL_CODEBASE: true
          VALIDATE_JAVA: true

  trivy:
    name: Docker Build and Trivy Scan
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: docker build -t demo-trivy-app .

      - name: Create reports directory
        run: mkdir -p trivy-reports

      - name: Trivy FS Scan (source code)
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: fs
          scan-ref: .
          format: table
          severity: CRITICAL,HIGH
          output: trivy-reports/fs-report.txt

      - name: Trivy Image Scan (Docker image)
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: image
          scan-ref: demo-trivy-app
          format: table
          severity: CRITICAL,HIGH
          output: trivy-reports/image-report.txt

      - name: Upload Trivy Reports
        uses: actions/upload-artifact@v4
        with:
          name: trivy-reports
          path: trivy-reports/
