name: Build & Trivy Scan

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build-and-scan:
    name: Build Docker Image and Run Trivy Scans
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: docker build -t demo-trivy-app .

      - name: Install Trivy
        uses: aquasecurity/trivy-action@master
        with:
          version: '0.50.1'

      - name: Trivy FS Scan (source code)
        run: |
          trivy fs . --format json --severity CRITICAL,HIGH --output trivy-fs-report.json
          trivy fs . --format table --severity CRITICAL,HIGH --output trivy-fs-report.txt

      - name: Trivy Image Scan (Docker image)
        run: |
          trivy image demo-trivy-app \
            --format json --severity CRITICAL,HIGH --output trivy-image-report.json
          trivy image demo-trivy-app \
            --format table --severity CRITICAL,HIGH --output trivy-image-report.txt

      - name: Upload Trivy Reports
        uses: actions/upload-artifact@v4
        with:
          name: trivy-reports
          path: |
            trivy-fs-report.*
            trivy-image-report.*
