name: Build and Deploy to Tomcat

on:
  push:
    branches:
      - main  # Trigger workflow on pushes to the 'main' branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up Java
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17' # Update based on your Java version

      # Step 3: Build with Maven
      - name: Build with Maven
        run: mvn clean package

      # Step 4: Deploy to Tomcat
      - name: Deploy to Tomcat
        env:
          TOMCAT_USER: ${{ secrets.TOMCAT_USER }}
          TOMCAT_PASSWORD: ${{ secrets.TOMCAT_PASSWORD }}
        run: |
          # Define variables
          WAR_FILE=target/*.war
          TOMCAT_URL=http://34.227.98.60:1234/manager/html/

          # Deploy WAR file
          curl -u "$TOMCAT_USER:$TOMCAT_PASSWORD" \
            --upload-file $WAR_FILE \
            "$TOMCAT_URL/deploy?path=/your-app-name&update=true"
