name: Build and Deploy to AWS Tomcat

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'

      - name: Build with Maven
        run: mvn clean install

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Deploy to AWS Tomcat
        run: |
          scp -r target/*.war ec2-user@<your-aws-instance-public-dns>:<tomcat-app-directory>
          ssh ec2-user@<your-aws-instance-public-dns> "cd <tomcat-app-directory> && sudo ./shutdown.sh"
          ssh ec2-user@<your-aws-instance-public-dns> "cd <tomcat-app-directory> && sudo ./startup.sh"
